name: Pushing to the Dev Staging Branch

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to Staging
    steps:
      - name: Deploy over SSH with Appleboy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.234.35.69
          username: ubuntu
          key: ${{ secrets.ID_RSA }}
          passphrase: ${{secrets.ID_RSA_PASSPHRASE}}
          port: 22
          script: |
            export PATH=$HOME/.nvm/versions/node/v22.18.0/bin:$PATH
            cd bmscicd/
            git pull


            if ! command -v pnpm &> /dev/null
            then
              echo "📦 pnpm not found. Installing..."
              npm install -g pnpm
            else
              echo "✅ pnpm already installed at $(which pnpm)"
            fi


            pnpm install --frozen-lockfile
            pnpm run build


            pm2 restart "Frontend Next"
            pm2 restart "WebSocket"
            pm2 restart "http-server"
